#\uD504\uB85C\uC81D\uD2B8 \uC774\uB984 \uC124\uC815 \uC608\uC2DC
#spring.application.name=basic

#\uC11C\uBC84 \uD3EC\uD2B8 \uAE30\uBCF8\uAC12\uC740 8080\uC785\uB2C8\uB2E4
#server.port=8080


server:
  port: 8080

spring:
  config:
    activate:
      on-profile: local
  # \uC544\uB798\uB294 jdbc\uC758 \uAE30\uBCF8 db \uAD00\uB828 \uC124\uC815\uC778\uB370, jdbc \uBFD0\uB9CC \uC544\uB2C8\uB77C mybatis / jpa \uB4F1 spring\uC758 \uB300\uBD80\uBD84\uC758 DB \uAE30\uC220\uC5D0 \uB3D9\uC77C\uD558\uAC8C \uC0AC\uC6A9
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://localhost:3306/board
    username: root
    password: 1234
  jpa:
    database: mysql
    # innoDB\uB97C \uC4F0\uACA0\uB2E4 \uB77C\uB294 \uC124\uC815
    database-platform: org.hibernate.dialect.MariaDBDialect
    # ddl \uBB38 \uC790\uB3D9\uC0DD\uC131 \uC5EC\uBD80 true. \uD14C\uC774\uBE14\uC740 \uC790\uB3D9\uC0DD\uC131(\uBC18\uC601)\uD574\uC8FC\uB098, \uC2A4\uD0A4\uB9C8\uB294 \uBC18\uB4DC\uC2DC \uC0AC\uC804\uC5D0 \uC0DD\uC131 \uD544\uC694
    generate-ddl: true
    # jpa(\uC778\uD130\uD398\uC774\uC2A4)\uC758 \uC2E4\uC9C8\uC801\uC778 \uAD6C\uD604\uCCB4\uB294 hibernate \uC774\uB2E4.
    hibernate:
      # create : \uB9E4\uBC88 table\uC744 drop\uD6C4 \uC7AC \uC0DD\uC131
      # update : entity \uBCC0\uACBD\uC0AC\uD56D\uB9CC alter\uB97C \uC801\uC6A9\uD558\uACE0 \uAE30\uC874 \uB370\uC774\uD130 \uC720\uC9C0
      # validate : \uC2E4\uC81C DB\uC640\uC758 \uCC28\uC774\uC810\uC744 check\uB9CC \uD558\uACE0 ddl \uBB38 \uC2E4\uD589 x, \uCF58\uC194\uB85C\uB9CC \uBCC0\uACBD\uC0AC\uD56D \uCD9C\uB825.
      ddl-auto: update
    # \uCF58\uC194\uCC3D\uC5D0 ddl, dml \uB4F1\uC758 \uCFFC\uB9AC\uB97C \uCD9C\uB825\uD558\uC5EC \uBCF4\uC5EC\uC8FC\uB294 \uC635\uC158
    show_sql: true

logging:
  level:
    # debug, info, error \uB85C\uADF8 \uCD9C\uB825
#    root: debug
    root: info # default

# mapper\uD30C\uC77C (mybatis\uC758 \uCFFC\uB9AC\uD30C\uC77C)\uC758 \uC704\uCE58\uB97C \uBA85\uC2DC\uD558\uACE0 scanning\uD55C\uB2E4. \uAE30\uBCF8\uC801\uC73C\uB85C resource\uD3F4\uB354\uB294 default.
mybatis:
  mapper-locations: classpath:/mapper/**/*.xml